"""
CSV to HTML Viewer
Creates a nicely formatted HTML table from CSV files.
Usage: python view_csv_html.py [csv_file_path]
"""

import pandas as pd
import sys
from pathlib import Path
import webbrowser
import tempfile


def create_html_view(file_path):
    """Create an HTML view of a CSV file and open in browser."""
    
    # Read CSV
    df = pd.read_csv(file_path)
    
    # If first column is unnamed index, use it as index
    if 'Unnamed: 0' in df.columns:
        df = df.set_index('Unnamed: 0')
        df.index.name = 'Feature'
    
    # Create HTML with nice styling
    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>{Path(file_path).name}</title>
        <style>
            body {{
                font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                margin: 20px;
                background-color: #f5f5f5;
            }}
            .container {{
                max-width: 1400px;
                margin: 0 auto;
                background-color: white;
                padding: 30px;
                border-radius: 10px;
                box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            }}
            h1 {{
                color: #2c3e50;
                border-bottom: 3px solid #3498db;
                padding-bottom: 10px;
            }}
            .info {{
                background-color: #ecf0f1;
                padding: 15px;
                border-radius: 5px;
                margin: 20px 0;
            }}
            .info p {{
                margin: 5px 0;
                color: #555;
            }}
            table {{
                width: 100%;
                border-collapse: collapse;
                margin-top: 20px;
            }}
            th {{
                background-color: #3498db;
                color: white;
                padding: 12px;
                text-align: left;
                font-weight: 600;
            }}
            td {{
                padding: 10px;
                border-bottom: 1px solid #ddd;
            }}
            tr:hover {{
                background-color: #f8f9fa;
            }}
            .numeric {{
                text-align: right;
                font-family: 'Courier New', monospace;
            }}
            .feature-name {{
                font-weight: 500;
                color: #2c3e50;
            }}
            .footer {{
                margin-top: 30px;
                text-align: center;
                color: #999;
                font-size: 12px;
            }}
        </style>
    </head>
    <body>
        <div class="container">
            <h1>📊 {Path(file_path).name}</h1>
            
            <div class="info">
                <p><strong>File Path:</strong> {file_path}</p>
                <p><strong>Shape:</strong> {df.shape[0]} rows × {df.shape[1]} columns</p>
                <p><strong>Numeric Columns:</strong> {len(df.select_dtypes(include='number').columns)}</p>
            </div>
            
            {df.to_html(classes='data-table', float_format=lambda x: f'{x:.6f}', border=0)}
            
            <div class="footer">
                <p>Generated by CSV Viewer | Week 4 Preprocessing</p>
            </div>
        </div>
        
        <script>
            // Add numeric class to numeric cells
            document.querySelectorAll('td').forEach(cell => {{
                if (!isNaN(cell.textContent) && cell.textContent.trim() !== '') {{
                    cell.classList.add('numeric');
                }}
            }});
            
            // Style feature names
            document.querySelectorAll('tbody tr th').forEach(cell => {{
                cell.classList.add('feature-name');
            }});
        </script>
    </body>
    </html>
    """
    
    # Save to temp file and open in browser
    with tempfile.NamedTemporaryFile(mode='w', suffix='.html', delete=False, encoding='utf-8') as f:
        f.write(html_content)
        temp_path = f.name
    
    print(f"✓ HTML view created: {temp_path}")
    print("Opening in browser...")
    webbrowser.open('file://' + temp_path)
    
    return temp_path


if __name__ == "__main__":
    if len(sys.argv) > 1:
        file_path = sys.argv[1]
    else:
        # Default to feature statistics
        file_path = "../data/processed/feature_statistics.csv"
    
    if not Path(file_path).exists():
        print(f"❌ File not found: {file_path}")
        print("\nUsage: python view_csv_html.py [csv_file_path]")
        print("Example: python view_csv_html.py ../data/processed/train.csv")
        sys.exit(1)
    
    create_html_view(file_path)
